export type Product = {
  id: number
  name: string
  tagline: string
  image: string
  category: string
  petType: string
  ingredients: string
  benefits: string[]
  usage: string
  conservation?: string
}

export const products: Product[] = [
  {
    id: 1,
    name: "La Garrita Verde",
    tagline: "Caldo de huesos + acelga, una bomba natural de nutrientes reales.",
    image: "/images/products/garrita-verde.jpg",
    category: "Garritas",
    petType: "Perros y Gatos",
    ingredients: "Caldo de huesos, acelga",
    benefits: [
      "Huesos y articulaciones fuertes: colageno y minerales del caldo de huesos",
      "Aporta hierro y minerales: la acelga ayuda a la vitalidad y energia diaria",
      "Mejora la digestion: fibra natural que cuida el intestino",
      "Piel sana y pelaje brillante: nutricion completa desde adentro",
      "Ayuda a la hidratacion: ideal para complementar la alimentacion",
    ],
    usage: "Perfecta como snack funcional o premio saludable.",
  },
  {
    id: 2,
    name: "La Garrita Huerta",
    tagline: "Caldo de huesos + manzana + zanahoria, 100% natural.",
    image: "/images/products/garrita-huerta.jpg",
    category: "Garritas",
    petType: "Perros y Gatos",
    ingredients: "Caldo de huesos, manzana, zanahoria",
    benefits: [
      "Articulaciones fuertes: colageno y minerales clave",
      "Mejor digestion: manzana y zanahoria ayudan al intestino y al transito",
      "Pelo mas sano y brillante: nutre piel y pelaje desde adentro",
      "Defensas arriba: vitaminas naturales que refuerzan el sistema inmune",
      "Mas hidratacion: ideal para los que toman poca agua",
    ],
    usage: "Natural, casera y hecha con amor.",
  },
  {
    id: 4,
    name: "La Garrita Dorada",
    tagline: "Caldo de huesos + calabaza + curcuma. Un snack funcional y poderoso.",
    image: "/images/products/garrita-dorada.jpg",
    category: "Garritas",
    petType: "Perros y Gatos",
    ingredients: "Caldo de huesos, calabaza, curcuma",
    benefits: [
      "Articulaciones fuertes: colageno y minerales del caldo de huesos",
      "Antiinflamatoria natural: la curcuma ayuda a aliviar molestias articulares",
      "Digestion mas liviana: la calabaza regula el transito intestinal",
      "Defensas mas fuertes: vitaminas y antioxidantes naturales",
      "Piel sana y pelaje brillante: nutricion que se nota por fuera",
      "Aporta hidratacion: ideal para complementar la alimentacion diaria",
    ],
    usage: "Perfecta como premio saludable o snack diario.",
  },
  {
    id: 5,
    name: "La Garrita Roja",
    tagline: "Caldo de huesos + remolacha. Nutricion real, natural y funcional.",
    image: "/images/products/garrita-roja.jpg",
    category: "Garritas",
    petType: "Perros y Gatos",
    ingredients: "Caldo de huesos, remolacha",
    benefits: [
      "Articulaciones fuertes: colageno y minerales del caldo de huesos",
      "Circulacion y energia natural: la remolacha favorece el flujo sanguineo",
      "Piel sana y pelaje fuerte: aminoacidos y minerales que nutren desde adentro",
      "Defensas mas fuertes: antioxidantes naturales que protegen el organismo",
      "Ayuda a desinflamar: ideal para perros activos o en recuperacion",
      "Mas hidratacion: snack humedo, sabroso y facil de digerir",
    ],
    usage: "Ideal como snack funcional o premio premium.",
  },
  {
    id: 7,
    name: "Caldo de Huesos Natural",
    tagline: "Un basico bien hecho, cocinado lento, sin vueltas y sin cosas raras.",
    image: "/images/products/caldo-huesos.jpg",
    category: "Caldos",
    petType: "Perros y Gatos",
    ingredients: "Huesos naturales",
    benefits: [
      "Fortalece huesos y articulaciones: rico en colageno y minerales naturales",
      "Hidrata y mejora la digestion: ideal para sumar liquido y sabor a la comida",
      "Piel sana y pelo brillante: nutricion que se nota desde afuera",
      "Abre el apetito: perfecto para perros y gatos mas selectivos",
    ],
    usage: "Venta por encargo. Se prepara fresco, con tiempo y amor.",
  },
  {
    id: 9,
    name: "Pate de Pollo Natural",
    tagline: "Nutricion real, como en casa. Pollo, caldo de huesos y calabaza.",
    image: "/images/products/pate-pollo.jpg",
    category: "Pates",
    petType: "Perros y Gatos",
    ingredients: "Pollo, caldo de huesos, calabaza",
    benefits: [
      "Aporta proteina de alta calidad",
      "Fortalece articulaciones y huesos",
      "Mejora la digestion y el transito intestinal",
      "Hidrata gracias al caldo de huesos",
      "Super sabroso: ideal para perris y gatitos exigentes",
    ],
    usage: "Solo como comida humeda, mezclado con balanceado. Ideal para cachorros, adultos y seniors.",
  },
  {
    id: 10,
    name: "Galletitas Caseras de Higado",
    tagline: "Un snack real, nutritivo y hecho con ingredientes simples.",
    image: "/images/products/galletitas-higado.jpg",
    category: "Galletitas",
    petType: "Perros",
    ingredients: "Higado, huevo, avena",
    benefits: [
      "El higado aporta vitaminas esenciales y hierro natural",
      "El huevo suma proteina de calidad para musculos sanos y pelaje brillante",
      "La avena acompana la digestion y es liviana de procesar",
    ],
    usage: "Comida de verdad, pensada para mimarlos como familia.",
  },
  {
    id: 11,
    name: "Pate Natural de Higado",
    tagline: "El higado es uno de los alimentos mas completos que existen.",
    image: "/images/products/pate-higado.jpg",
    category: "Pates",
    petType: "Perros y Gatos",
    ingredients: "Higado",
    benefits: [
      "Rico en hierro: ayuda a prevenir anemia",
      "Vitaminas A y complejo B: piel sana, pelo brillante y energia",
      "Alta palatabilidad: se lo devoran hasta los mas manosos",
      "Proteinas de calidad: ideal para crecimiento y recuperacion",
      "Refuerza defensas de forma natural",
    ],
    usage: "Como topping, premio de alto valor, para estimular el apetito. Ideal para viejitos, cachorros o animales en recuperacion.",
  },
  {
    id: 13,
    name: "Higado Deshidratado Natural",
    tagline: "100% higado deshidratado lento. Un clasico que les encanta.",
    image: "/images/products/higado-deshidratado.jpg",
    category: "Deshidratados",
    petType: "Perros y Gatos",
    ingredients: "100% higado",
    benefits: [
      "Rico en hierro: ayuda a prevenir anemia",
      "Alto en proteina: masa muscular fuerte",
      "Fuente natural de vitaminas A y B: defensas, piel y pelo sano",
      "Super palatable: ideal para perros y gatos exigentes",
    ],
    usage: "Snack ocasional, premio para entrenamiento, trozado sobre la comida. Dar con moderacion.",
    conservation: "Guardar en lugar fresco, seco y cerrado. Una vez abierto: consumir dentro de 30 dias.",
  },
  {
    id: 14,
    name: "Deshidratado de Pollo Natural",
    tagline: "Simple, noble y lleno de proteina real. 100% pollo.",
    image: "/images/products/pollo-deshidratado.jpg",
    category: "Deshidratados",
    petType: "Perros y Gatos",
    ingredients: "100% pollo",
    benefits: [
      "Alto en proteina de calidad",
      "Favorece el desarrollo muscular",
      "Facil de digerir, apto para estomagos sensibles",
    ],
    usage: "Snack saludable, premio para entrenar, topping para sumar sabor.",
    conservation: "Guardar en frasco hermetico, en lugar fresco y seco. Consumir dentro de 30 dias.",
  },
  {
    id: 15,
    name: "Gomita de Banana",
    tagline: "Un snack natural, funcional y riquisimo que suma amor.",
    image: "/images/products/gomita-banana.jpg",
    category: "Gomitas",
    petType: "Perros y Gatos",
    ingredients: "Banana natural, caldo de huesos",
    benefits: [
      "Aporta colageno natural",
      "Ayuda a la hidratacion diaria",
      "Super palatable, ideal como premio",
      "Banana: suave, dulce y facil de digerir",
    ],
    usage: "Como snack entre comidas, premio despues del paseo, ideal para dias de calor.",
  },
  {
    id: 16,
    name: "Gomita de Arandanos",
    tagline: "Un snack natural que suma sabor y bienestar en cada mordida.",
    image: "/images/products/gomita-arandanos.jpg",
    category: "Gomitas",
    petType: "Perros y Gatos",
    ingredients: "Arandanos naturales, caldo de huesos",
    benefits: [
      "Aporta colageno natural",
      "Favorece la hidratacion",
      "Super palatable y facil de masticar",
      "Arandanos: antioxidantes y llenos de sabor",
    ],
    usage: "Mantener refrigeradas. Consumir dentro del tiempo recomendado.",
    conservation: "Mantener refrigeradas. Evitar calor y exposicion directa al sol.",
  },
  {
    id: 17,
    name: "Gomita de Frutilla",
    tagline: "Un snack funcional, rico y natural que les encanta.",
    image: "/images/products/gomita-frutilla.jpg",
    category: "Gomitas",
    petType: "Perros y Gatos",
    ingredients: "Frutilla natural, caldo de huesos",
    benefits: [
      "Aporta colageno natural",
      "Ayuda a la hidratacion",
      "Ideal como premio o snack diario",
      "Frutilla natural: sabor suave y tentador",
    ],
    usage: "Mantener refrigerada. Consumir dentro de los dias recomendados.",
    conservation: "Mantener refrigerada. Evitar el calor y el sol directo.",
  },
  {
    id: 18,
    name: "Bastoncitos de Batata con Pollo",
    tagline: "Premios reales, simples y nutritivos. Sin vueltas.",
    image: "/images/products/bastoncito-batata-pollo.jpg",
    category: "Bastoncitos",
    petType: "Perros",
    ingredients: "Pollo, batata, avena",
    benefits: [
      "Altos en proteina gracias al pollo, para mantener masa muscular fuerte",
      "Energia natural y sostenida por la batata, ideal para perros activos",
      "Favorecen la digestion gracias a la fibra de la avena",
      "Sin conservantes ni quimicos",
      "Faciles de digerir y super palatables",
    ],
    usage: "Perfectos como premio diario o snack saludable entre comidas.",
  },
  {
    id: 19,
    name: "Bastoncitos de Remolacha con Pollo",
    tagline: "Color natural, nutricion real y sabor que los vuelve locos.",
    image: "/images/products/bastoncito-remolacha-pollo.jpg",
    category: "Bastoncitos",
    petType: "Perros",
    ingredients: "Pollo, remolacha, avena",
    benefits: [
      "Proteina de calidad para musculos fuertes y buena recuperacion",
      "Ricos en antioxidantes naturales gracias a la remolacha",
      "Contribuyen a una mejor circulacion y energia saludable",
      "Aportan fibra, ayudando a la digestion",
      "Sin conservantes, sin quimicos, sin rellenos innecesarios",
    ],
    usage: "Un snack distinto, nutritivo y funcional.",
  },
  {
    id: 20,
    name: "Bastoncitos de Calabaza con Pollo",
    tagline: "Snack saludable, simple y nutritivo.",
    image: "/images/products/bastoncito-calabaza-pollo.jpg",
    category: "Bastoncitos",
    petType: "Perros",
    ingredients: "Pollo, calabaza, avena",
    benefits: [
      "Proteina de calidad para mantener musculos fuertes",
      "Favorecen la digestion gracias a la fibra natural de la calabaza",
      "Ideales para perros con digestiones sensibles",
      "Aportan energia equilibrada",
      "Sin conservantes ni quimicos",
    ],
    usage: "Hechos con ingredientes reales, sin agregados innecesarios.",
  },
]

export const categories = [
  "Todos",
  "Garritas",
  "Caldos",
  "Pates",
  "Galletitas",
  "Deshidratados",
  "Gomitas",
  "Bastoncitos",
]
